import type { CSSProperties } from "react";
import Link from "next/link";

export const metadata={title:"Formats de tournoi | Tourneo",description:"Comparer championnat, poules, élimination directe et poules + finale avec avantages, limites et exemples."};

const formats=[
  {nom:"Championnat complet",ideal:"4 à 10 participants",plus:"Classement très représentatif, plusieurs matchs garantis.",moins:"Le nombre de rencontres augmente vite.",ex:"8 participants = 28 matchs."},
  {nom:"Phase de poules",ideal:"8 participants ou plus",plus:"Permet de répartir les matchs et de faire jouer tout le monde.",moins:"Nécessite une règle claire pour qualifier les meilleurs.",ex:"12 joueurs : 3 poules de 4, soit 18 matchs de poule."},
  {nom:"Élimination directe",ideal:"Quand le temps est limité",plus:"Simple, rapide et spectaculaire.",moins:"Un participant peut être éliminé après un seul match.",ex:"16 participants = 15 matchs pour désigner un vainqueur."},
  {nom:"Poules + phase finale",ideal:"Tournoi équilibré et compétitif",plus:"Plusieurs matchs garantis puis une fin à enjeu.",moins:"Organisation un peu plus longue et plus complexe.",ex:"16 joueurs : 4 poules de 4 puis quarts, demies et finale."},
];

export default function FormatsPage(){return <main style={s.page}><div style={s.shell}><header style={s.header}><Link href="/" style={s.brand}>TOURNEO</Link><nav style={s.nav}><Link href="/guides" style={s.navLink}>Guides</Link><Link href="/aide" style={s.navLink}>Aide</Link><Link href="/login" style={s.login}>Créer un tournoi</Link></nav></header><section style={s.hero}><span style={s.eyebrow}>Choisir le bon format</span><h1 style={s.title}>Le meilleur format dépend surtout du temps et du nombre de participants.</h1><p style={s.lead}>Il n'existe pas un format parfait pour tous les tournois. Le bon choix dépend du nombre de joueurs, du nombre de terrains, de la durée disponible et de l'importance que vous accordez à l'équité ou au suspense.</p></section><section style={s.grid}>{formats.map(f=><article style={s.card} key={f.nom}><h2 style={s.h2}>{f.nom}</h2><p style={s.meta}><strong>Idéal :</strong> {f.ideal}</p><p style={s.text}><strong>Avantage :</strong> {f.plus}</p><p style={s.text}><strong>Limite :</strong> {f.moins}</p><p style={s.example}>{f.ex}</p></article>)}</section><section style={s.choice}><h2 style={s.h2}>Comment décider rapidement ?</h2><p style={s.text}>Si vous avez peu de participants et assez de temps, privilégiez le championnat. Si vous avez beaucoup de participants, les poules permettent de structurer la compétition. Si le temps est court, l'élimination directe est la plus efficace. Si vous souhaitez que chacun joue plusieurs fois tout en gardant une finale, choisissez poules + phase finale.</p></section><section style={s.choice}><h2 style={s.h2}>Formule utile : nombre de matchs d'un championnat</h2><p style={s.text}>Pour n participants : n × (n - 1) ÷ 2. Exemples : 6 participants = 15 matchs, 8 = 28, 10 = 45. Cette progression explique pourquoi un championnat complet devient vite difficile à tenir sur une courte journée.</p></section></div></main>}
const s:Record<string,CSSProperties>={page:{minHeight:"100vh",padding:"0 18px 70px",background:"radial-gradient(circle at 15% 5%,rgba(124,92,255,.14),transparent 30%),linear-gradient(145deg,#050811,#0B1220)",color:"white",fontFamily:"Inter,system-ui,sans-serif"},shell:{maxWidth:1050,margin:"0 auto"},header:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,padding:"22px 0"},brand:{color:"white",fontWeight:950,textDecoration:"none",fontSize:22},nav:{display:"flex",gap:10,flexWrap:"wrap"},navLink:{color:"#B7C2D2",textDecoration:"none",padding:"10px"},login:{color:"white",textDecoration:"none",fontWeight:900,padding:"10px 14px",borderRadius:13,background:"linear-gradient(135deg,#7C5CFF,#3B82F6,#22D3EE)"},hero:{padding:"64px 0 34px"},eyebrow:{color:"#72E7FF",fontWeight:900,textTransform:"uppercase",letterSpacing:1.4,fontSize:11},title:{fontSize:"clamp(40px,7vw,66px)",lineHeight:1.02,margin:"10px 0 18px"},lead:{fontSize:18,lineHeight:1.75,color:"#B7C2D2",maxWidth:860},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:14,padding:"24px 0"},card:{padding:24,borderRadius:22,background:"rgba(15,25,43,.78)",border:"1px solid rgba(148,163,184,.14)"},h2:{margin:"0 0 12px",fontSize:23},meta:{color:"#72E7FF",lineHeight:1.6},text:{color:"#B7C2D2",lineHeight:1.75},example:{padding:"10px 12px",borderRadius:12,background:"rgba(124,92,255,.10)",color:"#D8D1FF",fontWeight:800},choice:{margin:"24px 0",padding:26,borderRadius:24,background:"rgba(15,25,43,.72)",border:"1px solid rgba(114,231,255,.16)"}};
