import type { CSSProperties } from "react";
import Link from "next/link";

export const metadata={title:"Aide Tourneo",description:"Aide sur les participants, QR joueur, scores, partage public, corrections et sécurité des tournois Tourneo."};

const faq=[
  ["Comment ajouter un participant ?","Vous pouvez ajouter manuellement un joueur ou une équipe, choisir un avatar ou une photo et lui attribuer une couleur. Lorsqu'un profil Tourneo est disponible, son identifiant peut aussi faciliter l'ajout."],
  ["À quoi sert le QR joueur ?","Il permet d'identifier rapidement un profil Tourneo et d'éviter de ressaisir les mêmes informations lorsque ce profil est ajouté à un tournoi."],
  ["Le public peut-il modifier les scores ?","Non. La page de partage public est pensée comme une consultation en lecture seule. La gestion du tournoi reste réservée à l'organisateur connecté."],
  ["Que faire en cas d'erreur de score ?","Corrigez le résultat dès que possible avant de poursuivre les étapes suivantes. En élimination directe, une correction sur un ancien tour peut nécessiter de reconstruire la suite du tableau."],
  ["Comment choisir le format ?","Le championnat convient aux petits groupes, les poules aux groupes plus importants, l'élimination directe aux contraintes de temps, et poules + finale à un compromis entre temps de jeu et enjeu final."],
  ["Tourneo remplace-t-il le règlement du tournoi ?","Non. L'organisateur reste responsable des règles sportives, de la sécurité, des décisions d'arbitrage et de la validation des participants."],
];

export default function AidePage(){return <main style={s.page}><div style={s.shell}><header style={s.header}><Link href="/" style={s.brand}>TOURNEO</Link><nav style={s.nav}><Link href="/guides" style={s.navLink}>Guides</Link><Link href="/formats-tournoi" style={s.navLink}>Formats</Link><Link href="/login" style={s.login}>Se connecter</Link></nav></header><section style={s.hero}><span style={s.eyebrow}>Centre d'aide</span><h1 style={s.title}>Comprendre Tourneo et organiser sereinement.</h1><p style={s.lead}>Cette page rassemble les réponses aux questions les plus fréquentes sur la création d'un tournoi, les participants, les scores et le partage.</p></section><section style={s.grid}>{faq.map(([q,a])=><article style={s.card} key={q}><h2 style={s.h2}>{q}</h2><p style={s.text}>{a}</p></article>)}</section><section style={s.notice}><h2 style={s.h2}>Bon réflexe avant le début</h2><p style={s.text}>Avant le premier match, vérifiez la liste des participants, le format choisi, les règles d'égalité et la durée prévue. Une correction à ce stade est beaucoup plus simple qu'en plein tournoi.</p></section><section style={s.links}><Link href="/guides" style={s.linkCard}><strong>Lire les guides</strong><span>Organisation, durée et bonnes pratiques.</span></Link><Link href="/formats-tournoi" style={s.linkCard}><strong>Comparer les formats</strong><span>Choisir la formule adaptée au nombre de joueurs.</span></Link><Link href="/contact" style={s.linkCard}><strong>Contacter Tourneo</strong><span>Signaler un problème ou poser une question.</span></Link></section></div></main>}
const s:Record<string,CSSProperties>={page:{minHeight:"100vh",padding:"0 18px 70px",background:"linear-gradient(145deg,#050811,#0B1220)",color:"white",fontFamily:"Inter,system-ui,sans-serif"},shell:{maxWidth:1050,margin:"0 auto"},header:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,padding:"22px 0"},brand:{color:"white",fontWeight:950,textDecoration:"none",fontSize:22},nav:{display:"flex",gap:10,flexWrap:"wrap"},navLink:{color:"#B7C2D2",textDecoration:"none",padding:"10px"},login:{color:"white",textDecoration:"none",fontWeight:900,padding:"10px 14px",borderRadius:13,background:"linear-gradient(135deg,#7C5CFF,#3B82F6,#22D3EE)"},hero:{padding:"64px 0 34px"},eyebrow:{color:"#72E7FF",fontWeight:900,textTransform:"uppercase",letterSpacing:1.4,fontSize:11},title:{fontSize:"clamp(40px,7vw,66px)",lineHeight:1.02,margin:"10px 0 18px"},lead:{fontSize:18,lineHeight:1.75,color:"#B7C2D2",maxWidth:850},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:14,padding:"24px 0"},card:{padding:24,borderRadius:22,background:"rgba(15,25,43,.78)",border:"1px solid rgba(148,163,184,.14)"},h2:{margin:"0 0 10px",fontSize:22},text:{margin:0,color:"#B7C2D2",lineHeight:1.8},notice:{margin:"30px 0",padding:26,borderRadius:24,background:"rgba(114,231,255,.06)",border:"1px solid rgba(114,231,255,.18)"},links:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14,marginTop:24},linkCard:{display:"flex",flexDirection:"column",gap:8,padding:22,borderRadius:20,background:"rgba(15,25,43,.72)",border:"1px solid rgba(148,163,184,.14)",color:"white",textDecoration:"none",lineHeight:1.6}};
