import type { CSSProperties } from "react";
import Link from "next/link";

export const metadata = { title:"Guides Tourneo | Organiser un tournoi", description:"Conseils pratiques pour préparer, chronométrer, arbitrer et partager un tournoi sportif." };

const guides = [
  ["1. Estimer la durée réelle", "Comptez le nombre de matchs, la durée moyenne d'une rencontre, les changements de terrain et une marge pour les retards. Une organisation réaliste vaut mieux qu'un planning trop serré."],
  ["2. Préparer les règles de départage", "Décidez avant le début comment gérer les égalités : différence de points, confrontation directe, points marqués ou match de barrage. Les participants doivent connaître la règle à l'avance."],
  ["3. Éviter les temps morts", "Affichez ou annoncez toujours le prochain match. Quand plusieurs terrains sont disponibles, préparez les rencontres suivantes pour éviter qu'un terrain reste vide."],
  ["4. Vérifier les scores", "Un score erroné peut modifier tout un classement. Faites confirmer les résultats litigieux rapidement, surtout avant le passage en phase finale."],
  ["5. Communiquer avec les participants", "Indiquez le point de rendez-vous, l'heure, le format, la durée estimée et la façon de consulter les résultats. Une bonne information réduit les interruptions pendant le tournoi."],
  ["6. Prévoir une fin claire", "Gardez quelques minutes pour annoncer le classement, le podium et remercier les participants. Un tournoi bien terminé laisse une meilleure impression qu'une fin précipitée."],
];

export default function GuidesPage(){return <main style={s.page}><div style={s.shell}><header style={s.header}><Link href="/" style={s.brand}>TOURNEO</Link><nav style={s.nav}><Link href="/formats-tournoi" style={s.navLink}>Formats</Link><Link href="/aide" style={s.navLink}>Aide</Link><Link href="/login" style={s.login}>Créer un tournoi</Link></nav></header><section style={s.hero}><span style={s.eyebrow}>Guides pratiques</span><h1 style={s.title}>Les bonnes pratiques qui rendent un tournoi plus fluide.</h1><p style={s.lead}>Ces guides sont pensés pour les petits et moyens tournois sportifs, amicaux ou associatifs. Ils donnent des repères simples pour organiser le temps, les règles, les scores et la communication.</p></section><section style={s.grid}>{guides.map(([t,txt])=><article style={s.card} key={t}><h2 style={s.h2}>{t}</h2><p style={s.text}>{txt}</p></article>)}</section><section style={s.tip}><h2 style={s.h2}>Exemple : tournoi de 8 joueurs en championnat</h2><p style={s.text}>Un championnat complet à 8 joueurs représente 28 matchs. Si chaque match dure 10 minutes et que vous avez un seul terrain, il faut déjà 4 h 40 de jeu pur. Avec deux terrains, environ 2 h 20, auxquels il faut ajouter les transitions et les pauses. Cette simple estimation permet souvent d'éviter de choisir un format trop long.</p></section><section style={s.links}><Link href="/formats-tournoi" style={s.linkCard}><strong>Comparer les formats</strong><span>Choisir entre championnat, poules et élimination.</span></Link><Link href="/aide" style={s.linkCard}><strong>Comprendre Tourneo</strong><span>QR, scores, partage public et profils.</span></Link></section></div></main>}
const s:Record<string,CSSProperties>={page:{minHeight:"100vh",padding:"0 18px 70px",background:"linear-gradient(145deg,#050811,#0B1220)",color:"white",fontFamily:"Inter,system-ui,sans-serif"},shell:{maxWidth:1050,margin:"0 auto"},header:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,padding:"22px 0"},brand:{color:"white",fontWeight:950,textDecoration:"none",fontSize:22},nav:{display:"flex",gap:10,flexWrap:"wrap"},navLink:{color:"#B7C2D2",textDecoration:"none",padding:"10px"},login:{color:"white",textDecoration:"none",fontWeight:900,padding:"10px 14px",borderRadius:13,background:"linear-gradient(135deg,#7C5CFF,#3B82F6,#22D3EE)"},hero:{padding:"64px 0 34px"},eyebrow:{color:"#72E7FF",fontWeight:900,textTransform:"uppercase",letterSpacing:1.4,fontSize:11},title:{fontSize:"clamp(40px,7vw,68px)",lineHeight:1.02,margin:"10px 0 18px"},lead:{fontSize:18,lineHeight:1.75,color:"#B7C2D2",maxWidth:850},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(290px,1fr))",gap:14,padding:"24px 0"},card:{padding:24,borderRadius:22,background:"rgba(15,25,43,.78)",border:"1px solid rgba(148,163,184,.14)"},h2:{margin:"0 0 10px",fontSize:22},text:{margin:0,color:"#B7C2D2",lineHeight:1.8},tip:{margin:"30px 0",padding:26,borderRadius:24,background:"rgba(114,231,255,.06)",border:"1px solid rgba(114,231,255,.18)"},links:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:14,marginTop:24},linkCard:{display:"flex",flexDirection:"column",gap:8,padding:22,borderRadius:20,background:"rgba(15,25,43,.72)",border:"1px solid rgba(148,163,184,.14)",color:"white",textDecoration:"none",lineHeight:1.6}};
